### ISSUE TITLE
authenticate with WebID

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-scala-js#5]
Need this so the server can determine what the user's personal profile is.
So this would be a login button on the Dashboard.

**Comment by bblfish** [comment]
this requires the client to know an authentication endpoint for the server, or for the user to enter one by hand. A default one should be settable  in the html.

**Comment by antonkulaga** [comment]
I was thinking about doing the same but with akka-http instead of play

**Comment by bblfish** [comment]
This project is front end, so it is neutral as to the backend, as long as they implement the [SoLiD](github.com/linkeddata/SoLiD) spec, which is under development.

**Comment by bblfish** [comment]
Questions:
- Where should the information be stored by the app? In a preferences graph? A global variable may do to start.
- If each remote URI returns the id of the user in a `User:` header, should one not ask each resource?  (not incompatible with user side preferences ). After all the user may be authenticated as a different user on each resource.
